// SPDX-License-Identifier: MIT
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace LinuxAvatarGuard
{
    public sealed class GuardShaders
    {
        static readonly HashSet<string> Allowed = new HashSet<string> {
            "lilToon", "Hidden/lilToonOutline", "Hidden/lilToonOutlineOnly",
            "Hidden/lilToonCutout", "Hidden/lilToonCutoutOutline",
            "Hidden/lilToonTransparent", "Hidden/lilToonTransparentOutline",
            "Hidden/lilToonOnePassTransparent", "Hidden/lilToonOnePassTransparentOutline",
            "Hidden/lilToonTwoPassTransparent", "Hidden/lilToonTwoPassTransparentOutline"
        };
        readonly string folder, buildId;
        readonly DecoderFragment decoder;
        readonly Dictionary<string, string> generated = new Dictionary<string, string>();
        public GuardShaders(string folder, string buildId) : this(folder, buildId, LegacyLinearCodecV1.Decoder) { }
        public GuardShaders(string folder, string buildId, DecoderFragment decoder)
        {
            this.folder = folder; this.buildId = buildId;
            this.decoder = decoder ?? throw new ArgumentNullException(nameof(decoder));
        }
        public static bool Supports(Shader s) => s != null && Allowed.Contains(s.name);
        public static string Property(int i) => "_LAGKey" + i;
        public static string Injection => LegacyLinearCodecV1.Decoder.Injection;
        public Shader Copy(Shader source)
        {
            var sourcePath = AssetDatabase.GetAssetPath(source);
            var license = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(sourcePath), "../LICENSE"));
            if (!File.Exists(license)) throw new InvalidOperationException("No se encontró la licencia de lilToon junto a sus fuentes.");
            string notice = folder + "/lilToon-LICENSE.txt";
            if (!File.Exists(notice)) File.Copy(license, notice);
            if (!Supports(source)) throw new InvalidOperationException("Variante lilToon no soportada: " + (source ? source.name : "null"));
            var name = Generate(source.name);
            AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
            var shader = Shader.Find(name);
            if (!shader || ShaderUtil.ShaderHasError(shader)) throw new InvalidOperationException("Falló la variante de shader: " + name);
            return shader;
        }
        string Generate(string name)
        {
            if (generated.TryGetValue(name, out var existing)) return existing;
            var source = Shader.Find(name);
            var path = AssetDatabase.GetAssetPath(source);
            if (!source || !path.EndsWith(".shader", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("Se requiere lilToon con fuentes .shader: " + name);
            string text = File.ReadAllText(path);
            if (text.Contains("LIL_CUSTOM_VERTEX_OS") || text.Contains("LIL_CUSTOM_PROPERTIES")) throw new InvalidOperationException("El shader ya tiene una personalización incompatible: " + name);
            text = "// Generated by Linux Avatar Guard. Derived from lilToon; see lilToon-LICENSE.txt.\n" + text;
            string targetName = "LinuxAvatarGuard/" + buildId + "/" + name;
            generated.Add(name, targetName);
            int shaderIndex = generated.Count;
            text = Regex.Replace(text, "(?m)^Shader\\s+\"[^\"]+\"", "Shader \"" + targetName + "\"");
            text = Regex.Replace(text, "UsePass\\s+\"([^\"]+)\"", match => {
                string reference = match.Groups[1].Value;
                int separator = reference.LastIndexOf('/');
                return "UsePass \"" + Generate(reference.Substring(0, separator)) + reference.Substring(separator) + "\"";
            });
            // Relative includes must resolve against the SOURCE, never the generated folder.
            text = Regex.Replace(text, "#include\\s+\"([^\"]+)\"", match => {
                string include = match.Groups[1].Value;
                if (include.StartsWith("Assets/") || include.StartsWith("Packages/") || include.EndsWith(".cginc")) return match.Value;
                var resolved = Path.GetFullPath(Path.Combine(Path.GetDirectoryName(path), include));
                return "#include \"" + FileUtil.GetProjectRelativePath(resolved) + "\"";
            });
            var properties = Regex.Match(text, "Properties\\s*\\{");
            if (!properties.Success) throw new InvalidOperationException("Shader sin Properties: " + name);
            string declarations = "\n";
            foreach (var property in decoder.RuntimeProperties) declarations += "[HideInInspector] " + property + " (\"OSC key\", Float) = 0\n";
            text = text.Insert(properties.Index + properties.Length, declarations);
            int sub = text.IndexOf("SubShader", StringComparison.Ordinal);
            if (sub < 0) throw new InvalidOperationException("Shader sin SubShader: " + name);
            text = text.Insert(sub, decoder.Injection);
            // lilToon's inspector can switch a protected material back to an unprotected shader.
            text = Regex.Replace(text, "CustomEditor\\s+\"[^\"]+\"", "CustomEditor \"LinuxAvatarGuard.ProtectedMaterialInspector\"");
            text = Regex.Replace(text, "Fallback\\s+\"[^\"]+\"", "Fallback Off");
            string output = folder + "/shader_" + shaderIndex + ".shader";
            File.WriteAllText(output, text);
            AssetDatabase.ImportAsset(output, ImportAssetOptions.ForceSynchronousImport);
            return targetName;
        }
    }
    public sealed class ProtectedMaterialInspector : ShaderGUI
    {
        public override void OnGUI(MaterialEditor editor, MaterialProperty[] properties)
        {
            EditorGUILayout.HelpBox(GuardText.Text("Material generado. Edita lilToon en el avatar original y vuelve a generar la copia. Las claves se aplican mediante OSC."), MessageType.Info);
        }
    }
}
